var annotated_dup =
[
    [ "A1", "Structures_8h.html#structA1", "Structures_8h_structA1" ],
    [ "AngularPowerSpectrum", "classAngularPowerSpectrum.html", "classAngularPowerSpectrum" ],
    [ "AngularPowerTH", "classAngularPowerTH.html", "classAngularPowerTH" ],
    [ "Astrophysics", "classAstrophysics.html", "classAstrophysics" ],
    [ "BiasMT", "classBiasMT.html", "classBiasMT" ],
    [ "Catalog", "classCatalog.html", "classCatalog" ],
    [ "Cl_FUNCTIONS", "classCl__FUNCTIONS.html", "classCl__FUNCTIONS" ],
    [ "cl_params", "AngularPowerSpectrum_8h.html#structcl__params", "AngularPowerSpectrum_8h_structcl__params" ],
    [ "CorrelationFunctionTH", "classCorrelationFunctionTH.html", "classCorrelationFunctionTH" ],
    [ "CosmoLib", "classCosmoLib.html", "classCosmoLib" ],
    [ "Cosmology", "classCosmology.html", "classCosmology" ],
    [ "Cwclass", "classCwclass.html", "classCwclass" ],
    [ "DensityProfiles", "classDensityProfiles.html", "classDensityProfiles" ],
    [ "DnDz", "classDnDz.html", "classDnDz" ],
    [ "experiments", "Structures_8h.html#structexperiments", "Structures_8h_structexperiments" ],
    [ "fftw_array", "classfftw__array.html", "classfftw__array" ],
    [ "FftwFunctions", "classFftwFunctions.html", "classFftwFunctions" ],
    [ "FileOutput", "classFileOutput.html", "classFileOutput" ],
    [ "gal_parameters", "Galaxy_8h.html#structgal__parameters", "Galaxy_8h_structgal__parameters" ],
    [ "GALAXY", "classGALAXY.html", "classGALAXY" ],
    [ "GnuplotC", "classGnuplotC.html", "classGnuplotC" ],
    [ "h", "namespace_3globalScope_4.html#classAngularPowerTH_1_1h", null ],
    [ "h", "namespace_3globalScope_4.html#classCl__FUNCTIONS_1_1h", null ],
    [ "HOD", "classHOD.html", "classHOD" ],
    [ "lss_vector", "classlss__vector.html", "classlss__vector" ],
    [ "MASS_BIAS_FUNCTIONS", "classMASS__BIAS__FUNCTIONS.html", "classMASS__BIAS__FUNCTIONS" ],
    [ "matrices", "Structures_8h.html#structmatrices", "Structures_8h_structmatrices" ],
    [ "McmcFunctions", "classMcmcFunctions.html", "classMcmcFunctions" ],
    [ "Message_error", "classMessage__error.html", "classMessage__error" ],
    [ "Parameters", "classParameters.html", "classParameters" ],
    [ "ParametersCosmolib", "classParametersCosmolib.html", "classParametersCosmolib" ],
    [ "ParametersF", "classParametersF.html", "classParametersF" ],
    [ "ParametersMCMC", "classParametersMCMC.html", "classParametersMCMC" ],
    [ "Params", "classParams.html", "classParams" ],
    [ "params_clth", "Structures_8h.html#structparams__clth", "Structures_8h_structparams__clth" ],
    [ "PowerSpectrum", "classPowerSpectrum.html", "classPowerSpectrum" ],
    [ "PowerSpectrumF", "classPowerSpectrumF.html", "classPowerSpectrumF" ],
    [ "prop_collection", "BiasMappingTechnique_8h.html#structprop__collection", "BiasMappingTechnique_8h_structprop__collection" ],
    [ "s_astrophysical_parameters", "Astrophysics_8h.html#structs__astrophysical__parameters", "Astrophysics_8h_structs__astrophysical__parameters" ],
    [ "s_aux", "Structures_8h.html#structs__aux", "Structures_8h_structs__aux" ],
    [ "s_bins_info", "structs__bins__info.html", "structs__bins__info" ],
    [ "s_cell_info", "Structures_8h.html#structs__cell__info", "Structures_8h_structs__cell__info" ],
    [ "s_cell_info_reduced", "structs__cell__info__reduced.html", "structs__cell__info__reduced" ],
    [ "s_CosmoInfo", "CosmologicalFunctions_8h.html#structs__CosmoInfo", "CosmologicalFunctions_8h_structs__CosmoInfo" ],
    [ "s_CosmologicalParameters", "Structures_8h.html#structs__CosmologicalParameters", "Structures_8h_structs__CosmologicalParameters" ],
    [ "s_data_structure", "Structures_8h.html#structs__data__structure", "Structures_8h_structs__data__structure" ],
    [ "s_data_structure_direct_sum", "Structures_8h.html#structs__data__structure__direct__sum", "Structures_8h_structs__data__structure__direct__sum" ],
    [ "s_Deltas", "Structures_8h.html#structs__Deltas", "Structures_8h_structs__Deltas" ],
    [ "s_dist_in_dmbins", "Structures_8h.html#structs__dist__in__dmbins", "Structures_8h_structs__dist__in__dmbins" ],
    [ "s_dndz", "DnDz_8h.html#structs__dndz", "DnDz_8h_structs__dndz" ],
    [ "s_eigen_vector", "structs__eigen__vector.html", "structs__eigen__vector" ],
    [ "s_Halo", "Structures_8h.html#structs__Halo", "Structures_8h_structs__Halo" ],
    [ "s_hods_par", "Hod_8h.html#structs__hods__par", "Hod_8h_structs__hods__par" ],
    [ "s_info_in_bins", "structs__info__in__bins.html", "structs__info__in__bins" ],
    [ "s_mass_members", "Structures_8h.html#structs__mass__members", "Structures_8h_structs__mass__members" ],
    [ "s_maximums", "Structures_8h.html#structs__maximums", "Structures_8h_structs__maximums" ],
    [ "s_message_pars", "structs__message__pars.html", "structs__message__pars" ],
    [ "s_minimums", "Structures_8h.html#structs__minimums", "Structures_8h_structs__minimums" ],
    [ "s_nearest_cells", "Structures_8h.html#structs__nearest__cells", "Structures_8h_structs__nearest__cells" ],
    [ "s_parameters_box", "Structures_8h.html#structs__parameters__box", "Structures_8h_structs__parameters__box" ],
    [ "s_parameters_estimator", "Structures_8h.html#structs__parameters__estimator", "Structures_8h_structs__parameters__estimator" ],
    [ "s_params_box_mas", "Structures_8h.html#structs__params__box__mas", "Structures_8h_structs__params__box__mas" ],
    [ "s_power_in_bins", "namespace_3globalScope_4.html#structs__power__in__bins", null ],
    [ "ScalingRelations", "classScalingRelations.html", "classScalingRelations" ],
    [ "ScreenOutput", "classScreenOutput.html", "classScreenOutput" ],
    [ "sizeChooser", "datatypes_8h.html#structsizeChooser", "datatypes_8h_structsizeChooser" ],
    [ "sizeChooserHelper", "datatypes_8h.html#structsizeChooserHelper", "datatypes_8h_structsizeChooserHelper" ],
    [ "sizeChooserHelper2", "datatypes_8h.html#structsizeChooserHelper2", "datatypes_8h_structsizeChooserHelper2" ],
    [ "sizeChooserHelper2< void, T2, T3 >", "datatypes_8h.html#structsizeChooserHelper2_3_01void_00_01T2_00_01T3_01_4", "datatypes_8h_structsizeChooserHelper2_3_01void_00_01T2_00_01T3_01_4" ],
    [ "sizeChooserHelper2< void, void, T3 >", "datatypes_8h.html#structsizeChooserHelper2_3_01void_00_01void_00_01T3_01_4", "datatypes_8h_structsizeChooserHelper2_3_01void_00_01void_00_01T3_01_4" ],
    [ "sizeChooserHelper2< void, void, void >", "datatypes_8h.html#structsizeChooserHelper2_3_01void_00_01void_00_01void_01_4", null ],
    [ "sizeChooserHelper< T, true >", "datatypes_8h.html#structsizeChooserHelper_3_01T_00_01true_01_4", "datatypes_8h_structsizeChooserHelper_3_01T_00_01true_01_4" ],
    [ "Statistics", "classStatistics.html", "classStatistics" ],
    [ "typehelper", "datatypes_8h.html#structtypehelper", null ],
    [ "typehelper< bool >", "structtypehelper_3_01bool_01_4.html", null ],
    [ "typehelper< float32 >", "structtypehelper_3_01float32_01_4.html", null ],
    [ "typehelper< float64 >", "structtypehelper_3_01float64_01_4.html", null ],
    [ "typehelper< int16 >", "structtypehelper_3_01int16_01_4.html", null ],
    [ "typehelper< int32 >", "structtypehelper_3_01int32_01_4.html", null ],
    [ "typehelper< int64 >", "structtypehelper_3_01int64_01_4.html", null ],
    [ "typehelper< int8 >", "structtypehelper_3_01int8_01_4.html", null ],
    [ "typehelper< std::string >", "structtypehelper_3_01std_1_1string_01_4.html", null ],
    [ "typehelper< uint16 >", "structtypehelper_3_01uint16_01_4.html", null ],
    [ "typehelper< uint32 >", "structtypehelper_3_01uint32_01_4.html", null ],
    [ "typehelper< uint64 >", "structtypehelper_3_01uint64_01_4.html", null ],
    [ "typehelper< uint8 >", "structtypehelper_3_01uint8_01_4.html", null ]
];