# ===================================================
# ===================================================
IC_index = 1
NX = 100
Redshift = 0.5
Nlambdath = 0
lambdath = 0
lambdath_v = 0
Realization = 1
Unitsim_plabel = 65
Quantity = DENSITY
smscale = 0
Type_of_file_X = bin
Name_Property_X = DENSITY
XNAME = DM_z
Input_Directory_X = /home/andres/data/Numerics/TNG/Iker/
Name_Catalog_X = densidad_CIC_256.bin
iMAS_X = 1
#-----------------------------------------------------------------------------------------
Input_Directory_BIAS_KERNEL = none
Input_Directory_BIAS_KERNEL_TWO = none
Input_Directory_X_REF = none
Input_Directory_X_REF_TWO = none
Name_Catalog_X_REF_PDF = none
Input_Directory_X_NEW = none
Name_Catalog_X_NEW = none

#-----------------------------------------------------------------------------------------
l_LOS_new_dm = 1 END
Number_of_chunks_new_dm = 1
iMAS_X_REF_PDF = 1
Name_VelFieldx_X = NOFILE
Name_VelFieldy_X = NOFILE
Name_VelFieldz_X = NOFILE
iMAS_X_NEW = 1
Apply_Rankordering = false
Convert_Density_to_Delta_X = true
Scale_X = log
delta_X_min = -1.
delta_X_max = 200.0
ldelta_X_min = 0.0
ldelta_X_max = 11.0
Type_of_file_Y = bin
Input_Directory_Y = /home/balaguera/data/Numerics/MODIFIED_GRAVITY/LCDM/HALOS/
Input_Directory_Y_TWO = none
Name_Catalog_Y = LCDM_HALOS_Ncounts_Nft256_MAS0.dat
Name_Property_Y = COUNTS
YNAME = TR
Name_Catalog_Y_HR =
iMAS_Y = 0
Convert_Density_to_Delta_Y = false
Scale_Y = linear
NY = 100
delta_Y_min = 0.0
delta_Y_max = 100.
ldelta_Y_min = -3.0
ldelta_Y_max = 3.0
NY_MASS = 300
NY_SAT_FRAC = 100
Redefine_limits = false
Write_PDF_number_counts = false
Comp_joint_PDF = false
Comp_conditional_PDF = false
write_files_for_histograms = false
N_SKNOT_MASSBIN = 50 #40
t_CWT_used = 1 2 3 4 END #when lambdath<0, more cells are classified as knots, whence we can use knots and the rest filaments
v_CWT_used = 1 2 34 END
N_iterations_Kernel = 200
Iterations_Kernel_average = 150
iteration_ini = 0
N_dm_realizations = 1
N_dm_initial = 1
N_iterations_dm = 0
x_OUTPUT_at_iteration = 200 END
Statistics = Pk_fkp
Name_survey = TNG_DM
Type_of_object = TRACER_REF
Output_directory = /home/andres/data/Numerics/TNG/Iker/
# ===================================================
Input_type = density_grid
Input_type_two = density_grid
ngal_delta = 1.0
Input_dir_cat = /home/balaguera/data/Numerics/MODIFIED_GRAVITY/LCDM/HALOS/
Input_dir_cat_TWO = none
Catalogue_file = fof_LCDM_normal.dat
# ===================================================

# These pparameter point to cat and number counts of that cat used as new reference in order to assign properties
# The DM of thes tracers is in Input_Directory_X_NEW/

Input_Directory_X_new_ref = none
Name_Catalog_X_new_ref = none
Input_dir_cat_new_ref = none
Catalogue_file_new_ref = none
Name_Catalog_Y_new_ref = none
Random_file = none
# ===================================================
delta_grid_file = /home/balaguera/data/Numerics/MODIFIED_GRAVITY/LCDM/HALOS/Ncounts_NGP_z0.5.bin
delta_grid_file2 = none
delta_grid_file3 = none
delta_grid_file4 = none
measure_cross = false
measure_cross_from_1 = 1
measure_cross_from_2 = 2
# ===================================================
sys_of_coord_dm = 0
i_coord1_dm = 0
i_coord2_dm = 1
i_coord3_dm = 2
i_v1_dm = 4
i_v2_dm = 5
i_v3_dm = 6
# ===================================================
sys_of_coord_g = 0
redshift_space_coords_g = false
i_coord1_g = 3
i_coord2_g = 4
i_coord3_g = 5
i_v1_g = -3
i_v2_g = -4
i_v3_g = -5
vel_units_g = kmps
i_mass_g = -2
i_vmax_g = -7
i_vrms_g = -8
i_rs_g = -9
i_spin_g = -10
i_b_to_a_g = -11
i_c_to_a_g = -12
i_virial_g = -13
i_rvir_g = -14
i_spin_bullock_g = -15
i_sf_g = -1
i_mean_density_g = -1
angles_units_g = D
i_weight1_g = -1
use_weight1_g = false
i_weight2_g = -1
use_weight1_g = false
i_weight3_g = -1
use_weight3_g = false
i_weight4_g = -1
use_weight4_g = false
weight_with_mass = false
weight_vel_with_mass = false
MASS_units = 1
NMASSbins_power = 4
NMASSbins = 200
LOGMASSmin = 0
VMAXmin = 160.0
RSmin = 1
SPINmin = 1e-5
LOGMASSmax = 16.0
VMAXmax = 1300.0
RSmax = 1200.0
SPINmax = 1.4
NMASSbins_mf = 200
NPROPbins_bam = 200 # ATENCION CON vmax_bins en def.h
#MASS BINS FOR POWER:
#m_MASSbins_min = 11.0 11.0 11.3 11.7 12.1 12.6 13.2 END  # INlcude always the full sample as the zerto-th bin
#n_MASSbins_max = 15.0 11.3 11.7 12.1 12.6 13.2 15.0 END
o_MASScuts = 12.0 13.0 END
#a_VMAXbins_min = 140.0 140.0 180.0 210.0 300.0 520.0 700.0 END
#b_VMAXbins_max = 1200.0 180.0 210.0 300.0 520.0 700.0 1100.0 END
set_bins_equal_number_tracers_main_property = false
Number_of_bins_equal_number_tracers_main_property = 5 #this is overriden if set_bins_equal_number_tracers_main_property = false
set_bins_equal_number_tracers = true
Number_of_bins_equal_number_tracers = 4
#these values (log M) are used in case Mvir is used as primary property for halo asswembly bias
m_MASSbins_min = 11.2 11.2 11.5 11.8 12.1 12.4 12.7 13.0 13.3 13.6 14.0 14.5 END  # INlcude always the full sample as the zerto-th bin
n_MASSbins_max = 15.0 11.5 11.8 12.1 12.4 13.7 13.0 13.3 13.6 14.0 14.5 15.0 END
#these values (log nu) are used in case peak height is used the primary property for halo asswembly bias
pm_PHbins_min = -0.3 -0.3 -0.2 -0.1 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 END  # INlcude always the full sample as the zerto-th bin
px_PHbins_max =  0.8 -0.2 -0.1  0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 END
#these values (log Vmax) are used in caseVmax is used as the primary property for halo asswembly bias
a_VMAXbins_min = 1.3 1.3 1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 END
b_VMAXbins_max = 3.3 1.5 1.7 1.9 2.1 2.3 2.5 2.7 2.9 3.1 3.3 END
k_RSbins_min = -1000.00 END
r_RSbins_max = 1000.0 END
kv_RVIRbins_min = 0.00 END
rv_RVIRbins_max = 10000.0 END
kc_CONCENTRATIONbins_min = 0.00 END
rc_CONCENTRATIONbins_max = 10000.0 END
q_SPINbins_min = 0.00 END
p_SPINbins_max = 20.000 END
qb_SPINbins_Bullock_min = 0.00 END
pb_SPINbins_Bullock_max = 20.000 END
w_VRMSbins_min = 0.00 END
z_VRMSbins_max = 2000.0 END
f_VIRbins_min = -10.0 END
g_VIRbins_max = 40.0 END
c_BTOAbins_min = 0.0 END
d_BTOAbins_max = 40.0 END
h_CTOAbins_min = 0.0 END
j_CTOAbins_max = 40.0 END
e_MACHbins_min = 0.0 END
i_MACHbins_max = 4000.0 END
e_DACHbins_min = 0.0 END
i_DACHbins_max = 4000.0 END
eb_BIASbins_min = -2000.0 END
ib_BIASbins_max = 2000.0 END
el_LCbins_min = -2000.0 END
il_LCbins_max = 2000.0 END
et_TAbins_min = -2000.0 END
it_TAbins_max = 2000.0 END
# ===================================================
#this overwrites the parameters above to do plots of bias for halo analysis
#ldelta_X_min = -1.0read_cat
#ldelta_X_max = 1.5
#ldelta_Y_min = -3.0
#ldelta_Y_max = 2.5
Nbins_hist = 200
use_real_and_redshift_space = false
Get_PCA = false
Get_pearson_coefficient = false
Get_marked_power_spectrum = false
Get_power_spectrum = false
Get_cross_power_spectrum = false
Get_tracer_number_counts = true
Get_tracer_mass_field = false
Get_tracer_vmax_field = false
Get_tracer_spin_field = false
Get_tracer_prop_function = false
Get_tracer_prop_function_cwt = false
Get_cell_local_mach_number = false
Get_tracer_local_mach_number = false
Get_tracer_local_dach_number = false
Get_tracer_local_dm_density = false
Scale_mach_number = 5.0
Get_local_overdensity = false
Get_tracer_bias = true
Get_tracer_relative_bias = false
Get_tracer_quadratic_bias = false
kmax_tracer_bias = 0.2
Get_tidal_anisotropy_at_halo = false
Get_peak_height_at_halo = false
# ===================================================
use_random_catalog = false
sys_of_coord_r = 2
i_coord1_r = 1
i_coord2_r = 2
i_coord3_r = 3
i_mean_density_r = 4
angles_unitGet_trs_r = D
i_weight1_r = 7
use_weight1_r = false
i_weight2_r = 15
use_weight2_r = false
i_weight3_r = 16
use_weight3_r = false
i_weight4_r = 17
use_weight4_r = false
nbar_tabulated = false
constant_depth = false
redshift_min_sample = 0.4
redshift_max_sample = 0.8
area_survey = 41253
get_window_matrix = false
# ===================================================
new_los = false
Nft_HR = 256
Nft = 256
Nft_low = 512
Lbox = 75
Lbox_low = 205
new_Lbox = false
mass_assignment_scheme = NGP
MAS_correction = false
type_of_binning = linear
DeltaKmin = 0.
N_log_bins = 10
ndel_data = 1
ndel_window = 1
N_mu_bins = 100
FKP_weight = false
Pest = 20000.0
SN_correction = false
FKP_error_bars = false
FKP_error_bars_exact = false
N_z_bins = 100
redshift_min_sample = 0
redshift_max_sample = 0.
N_dndz_bins = 100
new_N_dndz_bins = 60
file_power = bam
file_power_log = bam
xmin = 0
ymin = 0
zmin = 0
# ===================================================
Nbins_cf = 30
rmin_cf = 1.0
rmax_cf = 120.0
rbin_type = log
mark = mass
# ===================================================
u_PropThresholdMultiLevels = 700.0 500.0 350.0 300 250.0 END
q_NftMultiLevels = 16 32 64 128 180 END
s_PropToleranceMultiLevels = 0.95 0.9 0.9 0.8 0.7 END
Nft_random_collapse = 32
Distance_fraction = 0.35
M_exclusion = 5e13
use_vel_kernel = false
slengthv = 1.5
velbias_random = 0
velbias_dm = 0.0
# ===================================================
get_distribution_min_separations = false
# ===================================================
inputmode = 0
seed = 1
seed_ref = 0
runsim = true
runv = false
diffcosmorz = false
ic_power_file = Pk_Planck15_Table4.txt
ic_WN_file = none
ic_WN_dir = read_cat
ic_file = /home/balaguera/data/Numerics/UNITSIM/REFERENCE/001/IC/UNITSIM_fixed_amp_L1000_Nft256_IC1_CICc.dat
use_ic_file = true
ic_input_type = delta
Initial_Redshift_SIM = 99.0
Initial_Redshift_DELTA = 99.0
Normalize_IC_to_initial_redshift = false  #if IC are normalized at a z different of the initial redshift of simulation, set true
Initial_Redshift_TH_power_file = 0.0
dir = /home/balaguera/data/Numerics/UNITSIM/REFERENCE/001/IC/
Structure_Formation_Model = 3  # 1: ZELDOVICH; 2: 2LPT; 3: ALPT. >4: fastpm
transf = false
readPS = true
masskernel = 0 # 0: NGP, 1: CIC, 2:TSC
masskernel_vel = 1.0
slength = 10.0
velbias = 0.0
vslength = 0.0
# ===================================================
# ===================================================
file_bin_x_coord = /home/balaguera/data/Numerics/TNG/GALAXIES/x.bin
file_bin_y_coord = /home/balaguera/data/Numerics/TNG/GALAXIES/y.bin
file_bin_z_coord = /home/balaguera/data/Numerics/TNG/GALAXIES/z.bin
N_lines_binary = 429982 #244140625
use_low_pass_filter = false
# ===================================================
Number_of_GRF = 1000
Generate_FA = false
